#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

# Disable password authentication fo root user
ssh_pwauth: false

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

users:
  - name: swarm
    sudo: ALL=(ALL) NOPASSWD:ALL

# Install Docker + Docker Compose & Start Docker
runcmd:
  # Add repository
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  # Install Docker Engine
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl daemon-reload
  - systemctl restart docker
  - systemctl enable docker
  - docker swarm init
  # add user without direct root capabilities
  - usermod -aG sudo swarm
  - rsync --archive --verbose --chown=swarm:swarm /root/.ssh /home/swarm
   
final_message: "The system is ready, after $UPTIME seconds"
