version: '3.8'

services:
  traefik:
    container_name: traefik
    image: "traefik:v2.6"
    command:
      - "--log.level=DEBUG"
      - "--log.format=json"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=marc@becheftigt.de"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    volumes:
      - "./volumes/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${TRAEFIK_TAG}
  
  fluentd:
    container_name: fluentd
    build: ./fluentd
    restart: unless-stopped
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_USER: ${ELASTIC_USER}
      ELASTIC_PASS: ${ELASTIC_PASS}

  dancer:
    container_name: dancer
    image: dancier/dancer:1.0
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dancer.rule=Host(`${BACKEND_HOSTNAME}`)"
      - "traefik.http.routers.dancer.entrypoints=websecure"
      - "traefik.http.routers.dancer.tls.certresolver=mytlschallenge"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_AUTH_TOKENSECRET: ${APP_AUTH_TOKENSECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_MAIL_USER: ${APP_MAIL_USER}
      APP_MAIL_PASS: ${APP_MAIL_PASS}
      APP_CAPTCHA_APIKEY: ${APP_CAPTCHA_APIKEY}
    volumes:
      - ./volumes/dancer-media/images:/images-dir
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${DANCER_TAG}
    depends_on:
      - dancer-db
      - traefik
      - fluentd
      - iam

  dancer-db:
    container_name: dancer-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DANCER_DB_USER}
      POSTGRES_PASSWORD: ${DANCER_DB_PASSWORD}
      POSTGRES_DB: ${DANCER_DB_DB}
    volumes:
      - ./volumes/dancer-data:/var/lib/postgresql/data

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${PG_ADMIN_HOSTNAME}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=mytlschallenge"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dancier.net
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    depends_on:
      - dancer-db
      - traefik
    volumes:
      - ./volumes/pg-admin-data:/var/lib/pgadmin

  show-dancer:
    container_name: show-dancer
    image: dancier/show-dancer:${SHOW_DANCER_DEPLOY_TAG}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.show-dancer.rule=Host(`${SHOW_DANCER_HOSTNAME}`)"
      - "traefik.http.routers.show-dancer.entrypoints=websecure"
      - "traefik.http.routers.show-dancer.tls.certresolver=mytlschallenge"
    environment:
      DANCIER_BACKEND_URL: ${DANCIER_BACKEND_URL}
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${SHOW_DANCER_TAG}
    depends_on:
      - traefik
      - fluentd

  recommendation:
    container_name: recommendation
    image: dancier/recommendation:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - iam

  iam:
    container_name: iam
    image: quay.io/keycloak/keycloak:19.0.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-iam.rule=Host(`${IAM_HOST}`)"
      - "traefik.http.routers.test-iam.entrypoints=websecure"
      - "traefik.http.routers.test-iam.tls.certresolver=mytlschallenge"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 2s
      retries: 15
    environment:
       KC_PROXY: edge
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: ${IAM_ADMIN_PASSWD}
       KEYCLOAK_LOGLEVEL: INFO
       PROXY_ADDRESS_FORWARDING: "true"
    command:
      start-dev

  s3:
    container_name: s3
    image: minio/minio
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.s3.rule=Host(`${S3_HOST}`)"
      - "traefik.http.routers.s3.entrypoints=websecure"
      - "traefik.http.routers.s3.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.s3.service=s3"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"

      - "traefik.http.routers.s3-ui.rule=Host(`${S3_UI_HOST}`)"
      - "traefik.http.routers.s3-ui.entrypoints=websecure"
      - "traefik.http.routers.s3-ui.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.s3-ui.service=s3-ui"
      - "traefik.http.services.s3-ui.loadbalancer.server.port=9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: ${S3_ADMIN_PASSWD}
      MINIO_BROWSER_REDIRECT_URL: https://${S3_UI_HOST}
      MINIO_SERVER_URL: https://${S3_HOST}
    command: server /data --console-address ":9001"
    depends_on:
      - iam
  tool:
    container_name: tool
    image: ubuntu
    restart: unless-stopped
    stdin_open: true
