scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['dancer:8081']
    metric_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      replacement: "dancer_${1}"