scrape_configs:
  - job_name: 'dancer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['dancer:8081']
    metric_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      replacement: "dancer_${1}"
  - job_name: 'kikeriki'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['kikeriki:8081']
    metric_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      replacement: "kikeriki_${1}"
  - job_name: 'recommendation'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['recommendation:80']
    metric_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      replacement: "recommendation_${1}"

